### ISSUE TITLE
expected type torch.cuda.FloatTensor but got torch.FloatTensor

### ISSUE THREAD

**Issue by happyhugo** [JZhaoCH/cnnmrf-pytorch#1]
raceback (most recent call last):
  File "main.py", line 148, in <module>
    main(config)
  File "main.py", line 130, in main
    optimizer.step(closure)
  File "/jet/var/python/lib/python3.6/site-packages/torch/optim/lbfgs.py", line 213, in step
    loss = float(closure())
  File "main.py", line 120, in closure
    image = get_synthesis_image(synthesis, denorm_transform)
  File "main.py", line 32, in get_synthesis_image
    image = denorm(image).clamp_(0, 1)
  File "/jet/var/python/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/jet/var/python/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor

I run the code , found this problem

**Comment by JZhaoCH** [comment]
I think it's could be solved by init denorm_transform the delike this:

`denorm_transform = transforms.Normalize(mean=torch.tensor([-2.12, -2.04, -1.80]).to(device), std=torch.tensor([4.37, 4.46, 4.44]).to(device))`

Does it work?😀

**Comment by JZhaoCH** [comment]
the mean in denorm transform is a torch.FloatTensor, but the image is the torch.cuda.FloatTensor.😀

**Comment by jonzhaocn** [comment]
I think it's could be solved by initilizing denorm_transform the like this:

`denorm_transform = transforms.Normalize(mean=torch.tensor([-2.12, -2.04, -1.80]).to(device), std=torch.tensor([4.37, 4.46, 4.44]).to(device))`

Does it work?😃

the mean and std in denorm_transform is a torch.FloatTensor, but the image is the torch.cuda.FloatTensor.😃

**Comment by happyhugo** [comment]
it not work, the same error

res-1-iteration-10: 16.215366
res-1-iteration-20: 14.929934
res-1-iteration-30: 14.388243
res-1-iteration-40: 14.094181
res-1-iteration-50: 13.900432
/jet/var/python/lib/python3.6/site-packages/torchvision/transforms/functional.py:206: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mean = torch.tensor(mean, dtype=torch.float32)
/jet/var/python/lib/python3.6/site-packages/torchvision/transforms/functional.py:207: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  std = torch.tensor(std, dtype=torch.float32)
Traceback (most recent call last):
  File "main.py", line 148, in <module>
    main(config)
  File "main.py", line 130, in main
    optimizer.step(closure)
  File "/jet/var/python/lib/python3.6/site-packages/torch/optim/lbfgs.py", line 213, in step
    loss = float(closure())
  File "main.py", line 120, in closure
    image = get_synthesis_image(synthesis, denorm_transform)
  File "main.py", line 32, in get_synthesis_image
    image = denorm(image).clamp_(0, 1)
  File "/jet/var/python/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/jet/var/python/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor

i am not sure the warning is useful?

**Comment by jonzhaocn** [comment]
if you change the get_synthesis_image function to this:
```
def get_synthesis_image(synthesis, denorm):
    cpu_device = torch.device('cpu')
    image = synthesis.clone().squeeze().to(cpu_device)
    image = denorm(image).clamp_(0, 1)
    return image
```
does it work?😃

move image to cpu device before denorm function

**Comment by happyhugo** [comment]
good idea. it's useful. Thanks 😃
