### ISSUE TITLE
大佬想问下多尺度的问题

### ISSUE THREAD

**Issue by charmingjin** [JZhaoCH/cnnmrf-pytorch#3]
谢谢大佬提供的代码，我有个问题
content和style 的图片都是3层的金子塔结构，同时输入vgg提取特征，但是vgg的输入大小是固定的，那不同尺度下的图片输入vgg之前是不是都resize到了固定大小，还是vgg第一层的参数不同
谢谢

**Comment by jonzhaocn** [comment]
我是这样子做的：不同尺度下的图像直接输入到vgg中（直接输入，而不会resize到某一个大小）。

**Comment by charmingjin** [comment]
懂了 只不过同一个layer不同尺度得到的feature map 大小不同
谢谢大佬抽空回答

**Comment by jonzhaocn** [comment]
不用谢😃
