### ISSUE TITLE
有关于chuanli代码复现中computeBB的问题

### ISSUE THREAD

**Issue by MagaretJi** [JZhaoCH/cnnmrf-pytorch#4]
首先感谢大佬提供代码的思路，请问作者在mylib/helper中提到了computeBB函数的实现，请问对应在大佬代码哪里呢

**Comment by jonzhaocn** [comment]
你好，请问这个函数的功能是什么，可能我没有实现这个函数，我也看了作者的源码，其中有一部分关于图像旋转的功能 我没有实现。

**Comment by MagaretJi** [comment]
原来如此，这个就是有关图像旋转的部分，谢谢。
